// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whvdvuzkzcdtsdtfzdag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndodmR2dXpremNkdHNkdGZ6ZGFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNzI4NTMsImV4cCI6MjA2Njg0ODg1M30.8zic9mLVKb1K5NptCe_eaDGMesyGeAhCMJc96wmFZ1E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});